GET http://localhost:5000/movies/

###

POST http://localhost:5000/movies/
Content-Type: application/json

{
    "title": "Interstellar",
    "description": "Interstellar is a 2014 epic science fiction film co-written, directed and produced by Christopher Nolan. It stars Matthew McConaughey, Anne Hathaway, Jessica Chastain, Bill Irwin, Ellen Burstyn, Matt Damon, and Michael Caine. Set in a dystopian future where humanity is struggling to survive, the film follows a group of astronauts who travel through a wormhole near Saturn in search of a new home for mankind.",
    "releseDate": "10 19 2014"
}