GET http://localhost:5000/movies/

###

GET http://localhost:5000/movies/6318cfc50146139d0d649103

###

POST http://localhost:5000/movies/
Content-Type: application/json

{
    "title": "Your Name",
    "description": "One of the best anime movies.",
    "releseDate": "10 19 2014"
}

###

DELETE http://localhost:5000/movies/631f485276f7dd864294668d

###